name: flutter_stateful_bloc
description: A Flutter package that wraps the flutter_bloc package to easify working with it.
version: '0.0.5-beta'
repository: https://github.com/Mohamed-Shalabi/flutter-stateful-bloc
license: Apache-2.0

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.2
  meta: ^1.8.0
  bloc_test: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
